name: Run Tests

on:
  pull_request:
    branches: ["main"]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=True
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build/tests
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{github.workspace}}/build/tests/Testing/Temporary/LastTest.log
